---
- name: Deploy Blogging Website
  hosts: webserver
  become: yes
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy Website Files
      copy:
        src: /home/ec2-user/blogging-page/
        dest: /usr/share/nginx/html/
        owner: nginx
        group: nginx
        mode: "0755"

    - name: Configure Nginx
      template:
        src: nginx_config.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
